name       : hunspell-ro
version    : 3.3.10
release    : 1
source     :
    - http://netix.dl.sourceforge.net/project/rospell/Romanian%20dictionaries/dict-3.3.10/ro_RO.3.3.10.zip : 7f128d64ea06c9e6711c30b118c0afeefb014d8f33c92daccdf455aba2d04519
license    : CC-BY-3.0
component  : spelling
summary    : Romanian hunspell dictionaries
description: |
    Romanian hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -d -m 00644 $installdir/usr/share/hunspell
    install -m 00644 ro_RO.dic ro_RO.aff $installdir/usr/share/hunspell